
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/View'
export type * from './models/ViewOverride'
export type * from './models/DashboardConfig'
export type * from './models/MockVehicle'
export type * from './models/User'
export type * from './commonInputTypes'