
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ViewOverride` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ViewOverride
 * 
 */
export type ViewOverrideModel = runtime.Types.Result.DefaultSelection<Prisma.$ViewOverridePayload>

export type AggregateViewOverride = {
  _count: ViewOverrideCountAggregateOutputType | null
  _avg: ViewOverrideAvgAggregateOutputType | null
  _sum: ViewOverrideSumAggregateOutputType | null
  _min: ViewOverrideMinAggregateOutputType | null
  _max: ViewOverrideMaxAggregateOutputType | null
}

export type ViewOverrideAvgAggregateOutputType = {
  id: number | null
  posX: number | null
  posY: number | null
  posZ: number | null
  targetX: number | null
  targetY: number | null
  targetZ: number | null
}

export type ViewOverrideSumAggregateOutputType = {
  id: number | null
  posX: number | null
  posY: number | null
  posZ: number | null
  targetX: number | null
  targetY: number | null
  targetZ: number | null
}

export type ViewOverrideMinAggregateOutputType = {
  id: number | null
  viewKey: string | null
  posX: number | null
  posY: number | null
  posZ: number | null
  targetX: number | null
  targetY: number | null
  targetZ: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ViewOverrideMaxAggregateOutputType = {
  id: number | null
  viewKey: string | null
  posX: number | null
  posY: number | null
  posZ: number | null
  targetX: number | null
  targetY: number | null
  targetZ: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ViewOverrideCountAggregateOutputType = {
  id: number
  viewKey: number
  posX: number
  posY: number
  posZ: number
  targetX: number
  targetY: number
  targetZ: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ViewOverrideAvgAggregateInputType = {
  id?: true
  posX?: true
  posY?: true
  posZ?: true
  targetX?: true
  targetY?: true
  targetZ?: true
}

export type ViewOverrideSumAggregateInputType = {
  id?: true
  posX?: true
  posY?: true
  posZ?: true
  targetX?: true
  targetY?: true
  targetZ?: true
}

export type ViewOverrideMinAggregateInputType = {
  id?: true
  viewKey?: true
  posX?: true
  posY?: true
  posZ?: true
  targetX?: true
  targetY?: true
  targetZ?: true
  createdAt?: true
  updatedAt?: true
}

export type ViewOverrideMaxAggregateInputType = {
  id?: true
  viewKey?: true
  posX?: true
  posY?: true
  posZ?: true
  targetX?: true
  targetY?: true
  targetZ?: true
  createdAt?: true
  updatedAt?: true
}

export type ViewOverrideCountAggregateInputType = {
  id?: true
  viewKey?: true
  posX?: true
  posY?: true
  posZ?: true
  targetX?: true
  targetY?: true
  targetZ?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ViewOverrideAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ViewOverride to aggregate.
   */
  where?: Prisma.ViewOverrideWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ViewOverrides to fetch.
   */
  orderBy?: Prisma.ViewOverrideOrderByWithRelationInput | Prisma.ViewOverrideOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ViewOverrideWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ViewOverrides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ViewOverrides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ViewOverrides
  **/
  _count?: true | ViewOverrideCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ViewOverrideAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ViewOverrideSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ViewOverrideMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ViewOverrideMaxAggregateInputType
}

export type GetViewOverrideAggregateType<T extends ViewOverrideAggregateArgs> = {
      [P in keyof T & keyof AggregateViewOverride]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateViewOverride[P]>
    : Prisma.GetScalarType<T[P], AggregateViewOverride[P]>
}




export type ViewOverrideGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ViewOverrideWhereInput
  orderBy?: Prisma.ViewOverrideOrderByWithAggregationInput | Prisma.ViewOverrideOrderByWithAggregationInput[]
  by: Prisma.ViewOverrideScalarFieldEnum[] | Prisma.ViewOverrideScalarFieldEnum
  having?: Prisma.ViewOverrideScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ViewOverrideCountAggregateInputType | true
  _avg?: ViewOverrideAvgAggregateInputType
  _sum?: ViewOverrideSumAggregateInputType
  _min?: ViewOverrideMinAggregateInputType
  _max?: ViewOverrideMaxAggregateInputType
}

export type ViewOverrideGroupByOutputType = {
  id: number
  viewKey: string
  posX: number
  posY: number
  posZ: number
  targetX: number
  targetY: number
  targetZ: number
  createdAt: Date
  updatedAt: Date
  _count: ViewOverrideCountAggregateOutputType | null
  _avg: ViewOverrideAvgAggregateOutputType | null
  _sum: ViewOverrideSumAggregateOutputType | null
  _min: ViewOverrideMinAggregateOutputType | null
  _max: ViewOverrideMaxAggregateOutputType | null
}

export type GetViewOverrideGroupByPayload<T extends ViewOverrideGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ViewOverrideGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ViewOverrideGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ViewOverrideGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ViewOverrideGroupByOutputType[P]>
      }
    >
  >



export type ViewOverrideWhereInput = {
  AND?: Prisma.ViewOverrideWhereInput | Prisma.ViewOverrideWhereInput[]
  OR?: Prisma.ViewOverrideWhereInput[]
  NOT?: Prisma.ViewOverrideWhereInput | Prisma.ViewOverrideWhereInput[]
  id?: Prisma.IntFilter<"ViewOverride"> | number
  viewKey?: Prisma.StringFilter<"ViewOverride"> | string
  posX?: Prisma.FloatFilter<"ViewOverride"> | number
  posY?: Prisma.FloatFilter<"ViewOverride"> | number
  posZ?: Prisma.FloatFilter<"ViewOverride"> | number
  targetX?: Prisma.FloatFilter<"ViewOverride"> | number
  targetY?: Prisma.FloatFilter<"ViewOverride"> | number
  targetZ?: Prisma.FloatFilter<"ViewOverride"> | number
  createdAt?: Prisma.DateTimeFilter<"ViewOverride"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ViewOverride"> | Date | string
  view?: Prisma.XOR<Prisma.ViewScalarRelationFilter, Prisma.ViewWhereInput>
}

export type ViewOverrideOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  viewKey?: Prisma.SortOrder
  posX?: Prisma.SortOrder
  posY?: Prisma.SortOrder
  posZ?: Prisma.SortOrder
  targetX?: Prisma.SortOrder
  targetY?: Prisma.SortOrder
  targetZ?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  view?: Prisma.ViewOrderByWithRelationInput
}

export type ViewOverrideWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  viewKey?: string
  AND?: Prisma.ViewOverrideWhereInput | Prisma.ViewOverrideWhereInput[]
  OR?: Prisma.ViewOverrideWhereInput[]
  NOT?: Prisma.ViewOverrideWhereInput | Prisma.ViewOverrideWhereInput[]
  posX?: Prisma.FloatFilter<"ViewOverride"> | number
  posY?: Prisma.FloatFilter<"ViewOverride"> | number
  posZ?: Prisma.FloatFilter<"ViewOverride"> | number
  targetX?: Prisma.FloatFilter<"ViewOverride"> | number
  targetY?: Prisma.FloatFilter<"ViewOverride"> | number
  targetZ?: Prisma.FloatFilter<"ViewOverride"> | number
  createdAt?: Prisma.DateTimeFilter<"ViewOverride"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ViewOverride"> | Date | string
  view?: Prisma.XOR<Prisma.ViewScalarRelationFilter, Prisma.ViewWhereInput>
}, "id" | "viewKey">

export type ViewOverrideOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  viewKey?: Prisma.SortOrder
  posX?: Prisma.SortOrder
  posY?: Prisma.SortOrder
  posZ?: Prisma.SortOrder
  targetX?: Prisma.SortOrder
  targetY?: Prisma.SortOrder
  targetZ?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ViewOverrideCountOrderByAggregateInput
  _avg?: Prisma.ViewOverrideAvgOrderByAggregateInput
  _max?: Prisma.ViewOverrideMaxOrderByAggregateInput
  _min?: Prisma.ViewOverrideMinOrderByAggregateInput
  _sum?: Prisma.ViewOverrideSumOrderByAggregateInput
}

export type ViewOverrideScalarWhereWithAggregatesInput = {
  AND?: Prisma.ViewOverrideScalarWhereWithAggregatesInput | Prisma.ViewOverrideScalarWhereWithAggregatesInput[]
  OR?: Prisma.ViewOverrideScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ViewOverrideScalarWhereWithAggregatesInput | Prisma.ViewOverrideScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ViewOverride"> | number
  viewKey?: Prisma.StringWithAggregatesFilter<"ViewOverride"> | string
  posX?: Prisma.FloatWithAggregatesFilter<"ViewOverride"> | number
  posY?: Prisma.FloatWithAggregatesFilter<"ViewOverride"> | number
  posZ?: Prisma.FloatWithAggregatesFilter<"ViewOverride"> | number
  targetX?: Prisma.FloatWithAggregatesFilter<"ViewOverride"> | number
  targetY?: Prisma.FloatWithAggregatesFilter<"ViewOverride"> | number
  targetZ?: Prisma.FloatWithAggregatesFilter<"ViewOverride"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ViewOverride"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ViewOverride"> | Date | string
}

export type ViewOverrideCreateInput = {
  posX: number
  posY: number
  posZ: number
  targetX: number
  targetY: number
  targetZ: number
  createdAt?: Date | string
  updatedAt?: Date | string
  view: Prisma.ViewCreateNestedOneWithoutOverridesInput
}

export type ViewOverrideUncheckedCreateInput = {
  id?: number
  viewKey: string
  posX: number
  posY: number
  posZ: number
  targetX: number
  targetY: number
  targetZ: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ViewOverrideUpdateInput = {
  posX?: Prisma.FloatFieldUpdateOperationsInput | number
  posY?: Prisma.FloatFieldUpdateOperationsInput | number
  posZ?: Prisma.FloatFieldUpdateOperationsInput | number
  targetX?: Prisma.FloatFieldUpdateOperationsInput | number
  targetY?: Prisma.FloatFieldUpdateOperationsInput | number
  targetZ?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  view?: Prisma.ViewUpdateOneRequiredWithoutOverridesNestedInput
}

export type ViewOverrideUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  viewKey?: Prisma.StringFieldUpdateOperationsInput | string
  posX?: Prisma.FloatFieldUpdateOperationsInput | number
  posY?: Prisma.FloatFieldUpdateOperationsInput | number
  posZ?: Prisma.FloatFieldUpdateOperationsInput | number
  targetX?: Prisma.FloatFieldUpdateOperationsInput | number
  targetY?: Prisma.FloatFieldUpdateOperationsInput | number
  targetZ?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ViewOverrideCreateManyInput = {
  id?: number
  viewKey: string
  posX: number
  posY: number
  posZ: number
  targetX: number
  targetY: number
  targetZ: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ViewOverrideUpdateManyMutationInput = {
  posX?: Prisma.FloatFieldUpdateOperationsInput | number
  posY?: Prisma.FloatFieldUpdateOperationsInput | number
  posZ?: Prisma.FloatFieldUpdateOperationsInput | number
  targetX?: Prisma.FloatFieldUpdateOperationsInput | number
  targetY?: Prisma.FloatFieldUpdateOperationsInput | number
  targetZ?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ViewOverrideUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  viewKey?: Prisma.StringFieldUpdateOperationsInput | string
  posX?: Prisma.FloatFieldUpdateOperationsInput | number
  posY?: Prisma.FloatFieldUpdateOperationsInput | number
  posZ?: Prisma.FloatFieldUpdateOperationsInput | number
  targetX?: Prisma.FloatFieldUpdateOperationsInput | number
  targetY?: Prisma.FloatFieldUpdateOperationsInput | number
  targetZ?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ViewOverrideListRelationFilter = {
  every?: Prisma.ViewOverrideWhereInput
  some?: Prisma.ViewOverrideWhereInput
  none?: Prisma.ViewOverrideWhereInput
}

export type ViewOverrideOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ViewOverrideCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  viewKey?: Prisma.SortOrder
  posX?: Prisma.SortOrder
  posY?: Prisma.SortOrder
  posZ?: Prisma.SortOrder
  targetX?: Prisma.SortOrder
  targetY?: Prisma.SortOrder
  targetZ?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ViewOverrideAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  posX?: Prisma.SortOrder
  posY?: Prisma.SortOrder
  posZ?: Prisma.SortOrder
  targetX?: Prisma.SortOrder
  targetY?: Prisma.SortOrder
  targetZ?: Prisma.SortOrder
}

export type ViewOverrideMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  viewKey?: Prisma.SortOrder
  posX?: Prisma.SortOrder
  posY?: Prisma.SortOrder
  posZ?: Prisma.SortOrder
  targetX?: Prisma.SortOrder
  targetY?: Prisma.SortOrder
  targetZ?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ViewOverrideMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  viewKey?: Prisma.SortOrder
  posX?: Prisma.SortOrder
  posY?: Prisma.SortOrder
  posZ?: Prisma.SortOrder
  targetX?: Prisma.SortOrder
  targetY?: Prisma.SortOrder
  targetZ?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ViewOverrideSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  posX?: Prisma.SortOrder
  posY?: Prisma.SortOrder
  posZ?: Prisma.SortOrder
  targetX?: Prisma.SortOrder
  targetY?: Prisma.SortOrder
  targetZ?: Prisma.SortOrder
}

export type ViewOverrideCreateNestedManyWithoutViewInput = {
  create?: Prisma.XOR<Prisma.ViewOverrideCreateWithoutViewInput, Prisma.ViewOverrideUncheckedCreateWithoutViewInput> | Prisma.ViewOverrideCreateWithoutViewInput[] | Prisma.ViewOverrideUncheckedCreateWithoutViewInput[]
  connectOrCreate?: Prisma.ViewOverrideCreateOrConnectWithoutViewInput | Prisma.ViewOverrideCreateOrConnectWithoutViewInput[]
  createMany?: Prisma.ViewOverrideCreateManyViewInputEnvelope
  connect?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
}

export type ViewOverrideUncheckedCreateNestedManyWithoutViewInput = {
  create?: Prisma.XOR<Prisma.ViewOverrideCreateWithoutViewInput, Prisma.ViewOverrideUncheckedCreateWithoutViewInput> | Prisma.ViewOverrideCreateWithoutViewInput[] | Prisma.ViewOverrideUncheckedCreateWithoutViewInput[]
  connectOrCreate?: Prisma.ViewOverrideCreateOrConnectWithoutViewInput | Prisma.ViewOverrideCreateOrConnectWithoutViewInput[]
  createMany?: Prisma.ViewOverrideCreateManyViewInputEnvelope
  connect?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
}

export type ViewOverrideUpdateManyWithoutViewNestedInput = {
  create?: Prisma.XOR<Prisma.ViewOverrideCreateWithoutViewInput, Prisma.ViewOverrideUncheckedCreateWithoutViewInput> | Prisma.ViewOverrideCreateWithoutViewInput[] | Prisma.ViewOverrideUncheckedCreateWithoutViewInput[]
  connectOrCreate?: Prisma.ViewOverrideCreateOrConnectWithoutViewInput | Prisma.ViewOverrideCreateOrConnectWithoutViewInput[]
  upsert?: Prisma.ViewOverrideUpsertWithWhereUniqueWithoutViewInput | Prisma.ViewOverrideUpsertWithWhereUniqueWithoutViewInput[]
  createMany?: Prisma.ViewOverrideCreateManyViewInputEnvelope
  set?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
  disconnect?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
  delete?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
  connect?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
  update?: Prisma.ViewOverrideUpdateWithWhereUniqueWithoutViewInput | Prisma.ViewOverrideUpdateWithWhereUniqueWithoutViewInput[]
  updateMany?: Prisma.ViewOverrideUpdateManyWithWhereWithoutViewInput | Prisma.ViewOverrideUpdateManyWithWhereWithoutViewInput[]
  deleteMany?: Prisma.ViewOverrideScalarWhereInput | Prisma.ViewOverrideScalarWhereInput[]
}

export type ViewOverrideUncheckedUpdateManyWithoutViewNestedInput = {
  create?: Prisma.XOR<Prisma.ViewOverrideCreateWithoutViewInput, Prisma.ViewOverrideUncheckedCreateWithoutViewInput> | Prisma.ViewOverrideCreateWithoutViewInput[] | Prisma.ViewOverrideUncheckedCreateWithoutViewInput[]
  connectOrCreate?: Prisma.ViewOverrideCreateOrConnectWithoutViewInput | Prisma.ViewOverrideCreateOrConnectWithoutViewInput[]
  upsert?: Prisma.ViewOverrideUpsertWithWhereUniqueWithoutViewInput | Prisma.ViewOverrideUpsertWithWhereUniqueWithoutViewInput[]
  createMany?: Prisma.ViewOverrideCreateManyViewInputEnvelope
  set?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
  disconnect?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
  delete?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
  connect?: Prisma.ViewOverrideWhereUniqueInput | Prisma.ViewOverrideWhereUniqueInput[]
  update?: Prisma.ViewOverrideUpdateWithWhereUniqueWithoutViewInput | Prisma.ViewOverrideUpdateWithWhereUniqueWithoutViewInput[]
  updateMany?: Prisma.ViewOverrideUpdateManyWithWhereWithoutViewInput | Prisma.ViewOverrideUpdateManyWithWhereWithoutViewInput[]
  deleteMany?: Prisma.ViewOverrideScalarWhereInput | Prisma.ViewOverrideScalarWhereInput[]
}

export type ViewOverrideCreateWithoutViewInput = {
  posX: number
  posY: number
  posZ: number
  targetX: number
  targetY: number
  targetZ: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ViewOverrideUncheckedCreateWithoutViewInput = {
  id?: number
  posX: number
  posY: number
  posZ: number
  targetX: number
  targetY: number
  targetZ: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ViewOverrideCreateOrConnectWithoutViewInput = {
  where: Prisma.ViewOverrideWhereUniqueInput
  create: Prisma.XOR<Prisma.ViewOverrideCreateWithoutViewInput, Prisma.ViewOverrideUncheckedCreateWithoutViewInput>
}

export type ViewOverrideCreateManyViewInputEnvelope = {
  data: Prisma.ViewOverrideCreateManyViewInput | Prisma.ViewOverrideCreateManyViewInput[]
  skipDuplicates?: boolean
}

export type ViewOverrideUpsertWithWhereUniqueWithoutViewInput = {
  where: Prisma.ViewOverrideWhereUniqueInput
  update: Prisma.XOR<Prisma.ViewOverrideUpdateWithoutViewInput, Prisma.ViewOverrideUncheckedUpdateWithoutViewInput>
  create: Prisma.XOR<Prisma.ViewOverrideCreateWithoutViewInput, Prisma.ViewOverrideUncheckedCreateWithoutViewInput>
}

export type ViewOverrideUpdateWithWhereUniqueWithoutViewInput = {
  where: Prisma.ViewOverrideWhereUniqueInput
  data: Prisma.XOR<Prisma.ViewOverrideUpdateWithoutViewInput, Prisma.ViewOverrideUncheckedUpdateWithoutViewInput>
}

export type ViewOverrideUpdateManyWithWhereWithoutViewInput = {
  where: Prisma.ViewOverrideScalarWhereInput
  data: Prisma.XOR<Prisma.ViewOverrideUpdateManyMutationInput, Prisma.ViewOverrideUncheckedUpdateManyWithoutViewInput>
}

export type ViewOverrideScalarWhereInput = {
  AND?: Prisma.ViewOverrideScalarWhereInput | Prisma.ViewOverrideScalarWhereInput[]
  OR?: Prisma.ViewOverrideScalarWhereInput[]
  NOT?: Prisma.ViewOverrideScalarWhereInput | Prisma.ViewOverrideScalarWhereInput[]
  id?: Prisma.IntFilter<"ViewOverride"> | number
  viewKey?: Prisma.StringFilter<"ViewOverride"> | string
  posX?: Prisma.FloatFilter<"ViewOverride"> | number
  posY?: Prisma.FloatFilter<"ViewOverride"> | number
  posZ?: Prisma.FloatFilter<"ViewOverride"> | number
  targetX?: Prisma.FloatFilter<"ViewOverride"> | number
  targetY?: Prisma.FloatFilter<"ViewOverride"> | number
  targetZ?: Prisma.FloatFilter<"ViewOverride"> | number
  createdAt?: Prisma.DateTimeFilter<"ViewOverride"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ViewOverride"> | Date | string
}

export type ViewOverrideCreateManyViewInput = {
  id?: number
  posX: number
  posY: number
  posZ: number
  targetX: number
  targetY: number
  targetZ: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ViewOverrideUpdateWithoutViewInput = {
  posX?: Prisma.FloatFieldUpdateOperationsInput | number
  posY?: Prisma.FloatFieldUpdateOperationsInput | number
  posZ?: Prisma.FloatFieldUpdateOperationsInput | number
  targetX?: Prisma.FloatFieldUpdateOperationsInput | number
  targetY?: Prisma.FloatFieldUpdateOperationsInput | number
  targetZ?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ViewOverrideUncheckedUpdateWithoutViewInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  posX?: Prisma.FloatFieldUpdateOperationsInput | number
  posY?: Prisma.FloatFieldUpdateOperationsInput | number
  posZ?: Prisma.FloatFieldUpdateOperationsInput | number
  targetX?: Prisma.FloatFieldUpdateOperationsInput | number
  targetY?: Prisma.FloatFieldUpdateOperationsInput | number
  targetZ?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ViewOverrideUncheckedUpdateManyWithoutViewInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  posX?: Prisma.FloatFieldUpdateOperationsInput | number
  posY?: Prisma.FloatFieldUpdateOperationsInput | number
  posZ?: Prisma.FloatFieldUpdateOperationsInput | number
  targetX?: Prisma.FloatFieldUpdateOperationsInput | number
  targetY?: Prisma.FloatFieldUpdateOperationsInput | number
  targetZ?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ViewOverrideSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  viewKey?: boolean
  posX?: boolean
  posY?: boolean
  posZ?: boolean
  targetX?: boolean
  targetY?: boolean
  targetZ?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  view?: boolean | Prisma.ViewDefaultArgs<ExtArgs>
}, ExtArgs["result"]["viewOverride"]>

export type ViewOverrideSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  viewKey?: boolean
  posX?: boolean
  posY?: boolean
  posZ?: boolean
  targetX?: boolean
  targetY?: boolean
  targetZ?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  view?: boolean | Prisma.ViewDefaultArgs<ExtArgs>
}, ExtArgs["result"]["viewOverride"]>

export type ViewOverrideSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  viewKey?: boolean
  posX?: boolean
  posY?: boolean
  posZ?: boolean
  targetX?: boolean
  targetY?: boolean
  targetZ?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  view?: boolean | Prisma.ViewDefaultArgs<ExtArgs>
}, ExtArgs["result"]["viewOverride"]>

export type ViewOverrideSelectScalar = {
  id?: boolean
  viewKey?: boolean
  posX?: boolean
  posY?: boolean
  posZ?: boolean
  targetX?: boolean
  targetY?: boolean
  targetZ?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ViewOverrideOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "viewKey" | "posX" | "posY" | "posZ" | "targetX" | "targetY" | "targetZ" | "createdAt" | "updatedAt", ExtArgs["result"]["viewOverride"]>
export type ViewOverrideInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  view?: boolean | Prisma.ViewDefaultArgs<ExtArgs>
}
export type ViewOverrideIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  view?: boolean | Prisma.ViewDefaultArgs<ExtArgs>
}
export type ViewOverrideIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  view?: boolean | Prisma.ViewDefaultArgs<ExtArgs>
}

export type $ViewOverridePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ViewOverride"
  objects: {
    view: Prisma.$ViewPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    viewKey: string
    posX: number
    posY: number
    posZ: number
    targetX: number
    targetY: number
    targetZ: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["viewOverride"]>
  composites: {}
}

export type ViewOverrideGetPayload<S extends boolean | null | undefined | ViewOverrideDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload, S>

export type ViewOverrideCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ViewOverrideFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ViewOverrideCountAggregateInputType | true
  }

export interface ViewOverrideDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ViewOverride'], meta: { name: 'ViewOverride' } }
  /**
   * Find zero or one ViewOverride that matches the filter.
   * @param {ViewOverrideFindUniqueArgs} args - Arguments to find a ViewOverride
   * @example
   * // Get one ViewOverride
   * const viewOverride = await prisma.viewOverride.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ViewOverrideFindUniqueArgs>(args: Prisma.SelectSubset<T, ViewOverrideFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ViewOverrideClient<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ViewOverride that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ViewOverrideFindUniqueOrThrowArgs} args - Arguments to find a ViewOverride
   * @example
   * // Get one ViewOverride
   * const viewOverride = await prisma.viewOverride.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ViewOverrideFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ViewOverrideFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ViewOverrideClient<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ViewOverride that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewOverrideFindFirstArgs} args - Arguments to find a ViewOverride
   * @example
   * // Get one ViewOverride
   * const viewOverride = await prisma.viewOverride.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ViewOverrideFindFirstArgs>(args?: Prisma.SelectSubset<T, ViewOverrideFindFirstArgs<ExtArgs>>): Prisma.Prisma__ViewOverrideClient<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ViewOverride that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewOverrideFindFirstOrThrowArgs} args - Arguments to find a ViewOverride
   * @example
   * // Get one ViewOverride
   * const viewOverride = await prisma.viewOverride.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ViewOverrideFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ViewOverrideFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ViewOverrideClient<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ViewOverrides that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewOverrideFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ViewOverrides
   * const viewOverrides = await prisma.viewOverride.findMany()
   * 
   * // Get first 10 ViewOverrides
   * const viewOverrides = await prisma.viewOverride.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const viewOverrideWithIdOnly = await prisma.viewOverride.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ViewOverrideFindManyArgs>(args?: Prisma.SelectSubset<T, ViewOverrideFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ViewOverride.
   * @param {ViewOverrideCreateArgs} args - Arguments to create a ViewOverride.
   * @example
   * // Create one ViewOverride
   * const ViewOverride = await prisma.viewOverride.create({
   *   data: {
   *     // ... data to create a ViewOverride
   *   }
   * })
   * 
   */
  create<T extends ViewOverrideCreateArgs>(args: Prisma.SelectSubset<T, ViewOverrideCreateArgs<ExtArgs>>): Prisma.Prisma__ViewOverrideClient<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ViewOverrides.
   * @param {ViewOverrideCreateManyArgs} args - Arguments to create many ViewOverrides.
   * @example
   * // Create many ViewOverrides
   * const viewOverride = await prisma.viewOverride.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ViewOverrideCreateManyArgs>(args?: Prisma.SelectSubset<T, ViewOverrideCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ViewOverrides and returns the data saved in the database.
   * @param {ViewOverrideCreateManyAndReturnArgs} args - Arguments to create many ViewOverrides.
   * @example
   * // Create many ViewOverrides
   * const viewOverride = await prisma.viewOverride.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ViewOverrides and only return the `id`
   * const viewOverrideWithIdOnly = await prisma.viewOverride.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ViewOverrideCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ViewOverrideCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ViewOverride.
   * @param {ViewOverrideDeleteArgs} args - Arguments to delete one ViewOverride.
   * @example
   * // Delete one ViewOverride
   * const ViewOverride = await prisma.viewOverride.delete({
   *   where: {
   *     // ... filter to delete one ViewOverride
   *   }
   * })
   * 
   */
  delete<T extends ViewOverrideDeleteArgs>(args: Prisma.SelectSubset<T, ViewOverrideDeleteArgs<ExtArgs>>): Prisma.Prisma__ViewOverrideClient<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ViewOverride.
   * @param {ViewOverrideUpdateArgs} args - Arguments to update one ViewOverride.
   * @example
   * // Update one ViewOverride
   * const viewOverride = await prisma.viewOverride.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ViewOverrideUpdateArgs>(args: Prisma.SelectSubset<T, ViewOverrideUpdateArgs<ExtArgs>>): Prisma.Prisma__ViewOverrideClient<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ViewOverrides.
   * @param {ViewOverrideDeleteManyArgs} args - Arguments to filter ViewOverrides to delete.
   * @example
   * // Delete a few ViewOverrides
   * const { count } = await prisma.viewOverride.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ViewOverrideDeleteManyArgs>(args?: Prisma.SelectSubset<T, ViewOverrideDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ViewOverrides.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewOverrideUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ViewOverrides
   * const viewOverride = await prisma.viewOverride.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ViewOverrideUpdateManyArgs>(args: Prisma.SelectSubset<T, ViewOverrideUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ViewOverrides and returns the data updated in the database.
   * @param {ViewOverrideUpdateManyAndReturnArgs} args - Arguments to update many ViewOverrides.
   * @example
   * // Update many ViewOverrides
   * const viewOverride = await prisma.viewOverride.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ViewOverrides and only return the `id`
   * const viewOverrideWithIdOnly = await prisma.viewOverride.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ViewOverrideUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ViewOverrideUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ViewOverride.
   * @param {ViewOverrideUpsertArgs} args - Arguments to update or create a ViewOverride.
   * @example
   * // Update or create a ViewOverride
   * const viewOverride = await prisma.viewOverride.upsert({
   *   create: {
   *     // ... data to create a ViewOverride
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ViewOverride we want to update
   *   }
   * })
   */
  upsert<T extends ViewOverrideUpsertArgs>(args: Prisma.SelectSubset<T, ViewOverrideUpsertArgs<ExtArgs>>): Prisma.Prisma__ViewOverrideClient<runtime.Types.Result.GetResult<Prisma.$ViewOverridePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ViewOverrides.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewOverrideCountArgs} args - Arguments to filter ViewOverrides to count.
   * @example
   * // Count the number of ViewOverrides
   * const count = await prisma.viewOverride.count({
   *   where: {
   *     // ... the filter for the ViewOverrides we want to count
   *   }
   * })
  **/
  count<T extends ViewOverrideCountArgs>(
    args?: Prisma.Subset<T, ViewOverrideCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ViewOverrideCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ViewOverride.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewOverrideAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ViewOverrideAggregateArgs>(args: Prisma.Subset<T, ViewOverrideAggregateArgs>): Prisma.PrismaPromise<GetViewOverrideAggregateType<T>>

  /**
   * Group by ViewOverride.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewOverrideGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ViewOverrideGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ViewOverrideGroupByArgs['orderBy'] }
      : { orderBy?: ViewOverrideGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ViewOverrideGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetViewOverrideGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ViewOverride model
 */
readonly fields: ViewOverrideFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ViewOverride.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ViewOverrideClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  view<T extends Prisma.ViewDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ViewDefaultArgs<ExtArgs>>): Prisma.Prisma__ViewClient<runtime.Types.Result.GetResult<Prisma.$ViewPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ViewOverride model
 */
export interface ViewOverrideFieldRefs {
  readonly id: Prisma.FieldRef<"ViewOverride", 'Int'>
  readonly viewKey: Prisma.FieldRef<"ViewOverride", 'String'>
  readonly posX: Prisma.FieldRef<"ViewOverride", 'Float'>
  readonly posY: Prisma.FieldRef<"ViewOverride", 'Float'>
  readonly posZ: Prisma.FieldRef<"ViewOverride", 'Float'>
  readonly targetX: Prisma.FieldRef<"ViewOverride", 'Float'>
  readonly targetY: Prisma.FieldRef<"ViewOverride", 'Float'>
  readonly targetZ: Prisma.FieldRef<"ViewOverride", 'Float'>
  readonly createdAt: Prisma.FieldRef<"ViewOverride", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ViewOverride", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ViewOverride findUnique
 */
export type ViewOverrideFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * Filter, which ViewOverride to fetch.
   */
  where: Prisma.ViewOverrideWhereUniqueInput
}

/**
 * ViewOverride findUniqueOrThrow
 */
export type ViewOverrideFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * Filter, which ViewOverride to fetch.
   */
  where: Prisma.ViewOverrideWhereUniqueInput
}

/**
 * ViewOverride findFirst
 */
export type ViewOverrideFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * Filter, which ViewOverride to fetch.
   */
  where?: Prisma.ViewOverrideWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ViewOverrides to fetch.
   */
  orderBy?: Prisma.ViewOverrideOrderByWithRelationInput | Prisma.ViewOverrideOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ViewOverrides.
   */
  cursor?: Prisma.ViewOverrideWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ViewOverrides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ViewOverrides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ViewOverrides.
   */
  distinct?: Prisma.ViewOverrideScalarFieldEnum | Prisma.ViewOverrideScalarFieldEnum[]
}

/**
 * ViewOverride findFirstOrThrow
 */
export type ViewOverrideFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * Filter, which ViewOverride to fetch.
   */
  where?: Prisma.ViewOverrideWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ViewOverrides to fetch.
   */
  orderBy?: Prisma.ViewOverrideOrderByWithRelationInput | Prisma.ViewOverrideOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ViewOverrides.
   */
  cursor?: Prisma.ViewOverrideWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ViewOverrides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ViewOverrides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ViewOverrides.
   */
  distinct?: Prisma.ViewOverrideScalarFieldEnum | Prisma.ViewOverrideScalarFieldEnum[]
}

/**
 * ViewOverride findMany
 */
export type ViewOverrideFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * Filter, which ViewOverrides to fetch.
   */
  where?: Prisma.ViewOverrideWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ViewOverrides to fetch.
   */
  orderBy?: Prisma.ViewOverrideOrderByWithRelationInput | Prisma.ViewOverrideOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ViewOverrides.
   */
  cursor?: Prisma.ViewOverrideWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ViewOverrides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ViewOverrides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ViewOverrides.
   */
  distinct?: Prisma.ViewOverrideScalarFieldEnum | Prisma.ViewOverrideScalarFieldEnum[]
}

/**
 * ViewOverride create
 */
export type ViewOverrideCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * The data needed to create a ViewOverride.
   */
  data: Prisma.XOR<Prisma.ViewOverrideCreateInput, Prisma.ViewOverrideUncheckedCreateInput>
}

/**
 * ViewOverride createMany
 */
export type ViewOverrideCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ViewOverrides.
   */
  data: Prisma.ViewOverrideCreateManyInput | Prisma.ViewOverrideCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ViewOverride createManyAndReturn
 */
export type ViewOverrideCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * The data used to create many ViewOverrides.
   */
  data: Prisma.ViewOverrideCreateManyInput | Prisma.ViewOverrideCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ViewOverride update
 */
export type ViewOverrideUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * The data needed to update a ViewOverride.
   */
  data: Prisma.XOR<Prisma.ViewOverrideUpdateInput, Prisma.ViewOverrideUncheckedUpdateInput>
  /**
   * Choose, which ViewOverride to update.
   */
  where: Prisma.ViewOverrideWhereUniqueInput
}

/**
 * ViewOverride updateMany
 */
export type ViewOverrideUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ViewOverrides.
   */
  data: Prisma.XOR<Prisma.ViewOverrideUpdateManyMutationInput, Prisma.ViewOverrideUncheckedUpdateManyInput>
  /**
   * Filter which ViewOverrides to update
   */
  where?: Prisma.ViewOverrideWhereInput
  /**
   * Limit how many ViewOverrides to update.
   */
  limit?: number
}

/**
 * ViewOverride updateManyAndReturn
 */
export type ViewOverrideUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * The data used to update ViewOverrides.
   */
  data: Prisma.XOR<Prisma.ViewOverrideUpdateManyMutationInput, Prisma.ViewOverrideUncheckedUpdateManyInput>
  /**
   * Filter which ViewOverrides to update
   */
  where?: Prisma.ViewOverrideWhereInput
  /**
   * Limit how many ViewOverrides to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ViewOverride upsert
 */
export type ViewOverrideUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * The filter to search for the ViewOverride to update in case it exists.
   */
  where: Prisma.ViewOverrideWhereUniqueInput
  /**
   * In case the ViewOverride found by the `where` argument doesn't exist, create a new ViewOverride with this data.
   */
  create: Prisma.XOR<Prisma.ViewOverrideCreateInput, Prisma.ViewOverrideUncheckedCreateInput>
  /**
   * In case the ViewOverride was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ViewOverrideUpdateInput, Prisma.ViewOverrideUncheckedUpdateInput>
}

/**
 * ViewOverride delete
 */
export type ViewOverrideDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
  /**
   * Filter which ViewOverride to delete.
   */
  where: Prisma.ViewOverrideWhereUniqueInput
}

/**
 * ViewOverride deleteMany
 */
export type ViewOverrideDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ViewOverrides to delete
   */
  where?: Prisma.ViewOverrideWhereInput
  /**
   * Limit how many ViewOverrides to delete.
   */
  limit?: number
}

/**
 * ViewOverride without action
 */
export type ViewOverrideDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOverride
   */
  select?: Prisma.ViewOverrideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOverride
   */
  omit?: Prisma.ViewOverrideOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOverrideInclude<ExtArgs> | null
}
