
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DashboardConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DashboardConfig
 * 
 */
export type DashboardConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$DashboardConfigPayload>

export type AggregateDashboardConfig = {
  _count: DashboardConfigCountAggregateOutputType | null
  _min: DashboardConfigMinAggregateOutputType | null
  _max: DashboardConfigMaxAggregateOutputType | null
}

export type DashboardConfigMinAggregateOutputType = {
  key: string | null
}

export type DashboardConfigMaxAggregateOutputType = {
  key: string | null
}

export type DashboardConfigCountAggregateOutputType = {
  key: number
  data: number
  _all: number
}


export type DashboardConfigMinAggregateInputType = {
  key?: true
}

export type DashboardConfigMaxAggregateInputType = {
  key?: true
}

export type DashboardConfigCountAggregateInputType = {
  key?: true
  data?: true
  _all?: true
}

export type DashboardConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DashboardConfig to aggregate.
   */
  where?: Prisma.DashboardConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DashboardConfigs to fetch.
   */
  orderBy?: Prisma.DashboardConfigOrderByWithRelationInput | Prisma.DashboardConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DashboardConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DashboardConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DashboardConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DashboardConfigs
  **/
  _count?: true | DashboardConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DashboardConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DashboardConfigMaxAggregateInputType
}

export type GetDashboardConfigAggregateType<T extends DashboardConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateDashboardConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDashboardConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateDashboardConfig[P]>
}




export type DashboardConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DashboardConfigWhereInput
  orderBy?: Prisma.DashboardConfigOrderByWithAggregationInput | Prisma.DashboardConfigOrderByWithAggregationInput[]
  by: Prisma.DashboardConfigScalarFieldEnum[] | Prisma.DashboardConfigScalarFieldEnum
  having?: Prisma.DashboardConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DashboardConfigCountAggregateInputType | true
  _min?: DashboardConfigMinAggregateInputType
  _max?: DashboardConfigMaxAggregateInputType
}

export type DashboardConfigGroupByOutputType = {
  key: string
  data: runtime.JsonValue
  _count: DashboardConfigCountAggregateOutputType | null
  _min: DashboardConfigMinAggregateOutputType | null
  _max: DashboardConfigMaxAggregateOutputType | null
}

export type GetDashboardConfigGroupByPayload<T extends DashboardConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DashboardConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DashboardConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DashboardConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DashboardConfigGroupByOutputType[P]>
      }
    >
  >



export type DashboardConfigWhereInput = {
  AND?: Prisma.DashboardConfigWhereInput | Prisma.DashboardConfigWhereInput[]
  OR?: Prisma.DashboardConfigWhereInput[]
  NOT?: Prisma.DashboardConfigWhereInput | Prisma.DashboardConfigWhereInput[]
  key?: Prisma.StringFilter<"DashboardConfig"> | string
  data?: Prisma.JsonFilter<"DashboardConfig">
}

export type DashboardConfigOrderByWithRelationInput = {
  key?: Prisma.SortOrder
  data?: Prisma.SortOrder
}

export type DashboardConfigWhereUniqueInput = Prisma.AtLeast<{
  key?: string
  AND?: Prisma.DashboardConfigWhereInput | Prisma.DashboardConfigWhereInput[]
  OR?: Prisma.DashboardConfigWhereInput[]
  NOT?: Prisma.DashboardConfigWhereInput | Prisma.DashboardConfigWhereInput[]
  data?: Prisma.JsonFilter<"DashboardConfig">
}, "key">

export type DashboardConfigOrderByWithAggregationInput = {
  key?: Prisma.SortOrder
  data?: Prisma.SortOrder
  _count?: Prisma.DashboardConfigCountOrderByAggregateInput
  _max?: Prisma.DashboardConfigMaxOrderByAggregateInput
  _min?: Prisma.DashboardConfigMinOrderByAggregateInput
}

export type DashboardConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.DashboardConfigScalarWhereWithAggregatesInput | Prisma.DashboardConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.DashboardConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DashboardConfigScalarWhereWithAggregatesInput | Prisma.DashboardConfigScalarWhereWithAggregatesInput[]
  key?: Prisma.StringWithAggregatesFilter<"DashboardConfig"> | string
  data?: Prisma.JsonWithAggregatesFilter<"DashboardConfig">
}

export type DashboardConfigCreateInput = {
  key: string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type DashboardConfigUncheckedCreateInput = {
  key: string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type DashboardConfigUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type DashboardConfigUncheckedUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type DashboardConfigCreateManyInput = {
  key: string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type DashboardConfigUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type DashboardConfigUncheckedUpdateManyInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type DashboardConfigCountOrderByAggregateInput = {
  key?: Prisma.SortOrder
  data?: Prisma.SortOrder
}

export type DashboardConfigMaxOrderByAggregateInput = {
  key?: Prisma.SortOrder
}

export type DashboardConfigMinOrderByAggregateInput = {
  key?: Prisma.SortOrder
}



export type DashboardConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  data?: boolean
}, ExtArgs["result"]["dashboardConfig"]>

export type DashboardConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  data?: boolean
}, ExtArgs["result"]["dashboardConfig"]>

export type DashboardConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  data?: boolean
}, ExtArgs["result"]["dashboardConfig"]>

export type DashboardConfigSelectScalar = {
  key?: boolean
  data?: boolean
}

export type DashboardConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"key" | "data", ExtArgs["result"]["dashboardConfig"]>

export type $DashboardConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DashboardConfig"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    key: string
    data: runtime.JsonValue
  }, ExtArgs["result"]["dashboardConfig"]>
  composites: {}
}

export type DashboardConfigGetPayload<S extends boolean | null | undefined | DashboardConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload, S>

export type DashboardConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DashboardConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DashboardConfigCountAggregateInputType | true
  }

export interface DashboardConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DashboardConfig'], meta: { name: 'DashboardConfig' } }
  /**
   * Find zero or one DashboardConfig that matches the filter.
   * @param {DashboardConfigFindUniqueArgs} args - Arguments to find a DashboardConfig
   * @example
   * // Get one DashboardConfig
   * const dashboardConfig = await prisma.dashboardConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DashboardConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, DashboardConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DashboardConfigClient<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DashboardConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DashboardConfigFindUniqueOrThrowArgs} args - Arguments to find a DashboardConfig
   * @example
   * // Get one DashboardConfig
   * const dashboardConfig = await prisma.dashboardConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DashboardConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DashboardConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DashboardConfigClient<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DashboardConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DashboardConfigFindFirstArgs} args - Arguments to find a DashboardConfig
   * @example
   * // Get one DashboardConfig
   * const dashboardConfig = await prisma.dashboardConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DashboardConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, DashboardConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__DashboardConfigClient<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DashboardConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DashboardConfigFindFirstOrThrowArgs} args - Arguments to find a DashboardConfig
   * @example
   * // Get one DashboardConfig
   * const dashboardConfig = await prisma.dashboardConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DashboardConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DashboardConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DashboardConfigClient<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DashboardConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DashboardConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DashboardConfigs
   * const dashboardConfigs = await prisma.dashboardConfig.findMany()
   * 
   * // Get first 10 DashboardConfigs
   * const dashboardConfigs = await prisma.dashboardConfig.findMany({ take: 10 })
   * 
   * // Only select the `key`
   * const dashboardConfigWithKeyOnly = await prisma.dashboardConfig.findMany({ select: { key: true } })
   * 
   */
  findMany<T extends DashboardConfigFindManyArgs>(args?: Prisma.SelectSubset<T, DashboardConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DashboardConfig.
   * @param {DashboardConfigCreateArgs} args - Arguments to create a DashboardConfig.
   * @example
   * // Create one DashboardConfig
   * const DashboardConfig = await prisma.dashboardConfig.create({
   *   data: {
   *     // ... data to create a DashboardConfig
   *   }
   * })
   * 
   */
  create<T extends DashboardConfigCreateArgs>(args: Prisma.SelectSubset<T, DashboardConfigCreateArgs<ExtArgs>>): Prisma.Prisma__DashboardConfigClient<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DashboardConfigs.
   * @param {DashboardConfigCreateManyArgs} args - Arguments to create many DashboardConfigs.
   * @example
   * // Create many DashboardConfigs
   * const dashboardConfig = await prisma.dashboardConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DashboardConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, DashboardConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DashboardConfigs and returns the data saved in the database.
   * @param {DashboardConfigCreateManyAndReturnArgs} args - Arguments to create many DashboardConfigs.
   * @example
   * // Create many DashboardConfigs
   * const dashboardConfig = await prisma.dashboardConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DashboardConfigs and only return the `key`
   * const dashboardConfigWithKeyOnly = await prisma.dashboardConfig.createManyAndReturn({
   *   select: { key: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DashboardConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DashboardConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DashboardConfig.
   * @param {DashboardConfigDeleteArgs} args - Arguments to delete one DashboardConfig.
   * @example
   * // Delete one DashboardConfig
   * const DashboardConfig = await prisma.dashboardConfig.delete({
   *   where: {
   *     // ... filter to delete one DashboardConfig
   *   }
   * })
   * 
   */
  delete<T extends DashboardConfigDeleteArgs>(args: Prisma.SelectSubset<T, DashboardConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__DashboardConfigClient<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DashboardConfig.
   * @param {DashboardConfigUpdateArgs} args - Arguments to update one DashboardConfig.
   * @example
   * // Update one DashboardConfig
   * const dashboardConfig = await prisma.dashboardConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DashboardConfigUpdateArgs>(args: Prisma.SelectSubset<T, DashboardConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__DashboardConfigClient<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DashboardConfigs.
   * @param {DashboardConfigDeleteManyArgs} args - Arguments to filter DashboardConfigs to delete.
   * @example
   * // Delete a few DashboardConfigs
   * const { count } = await prisma.dashboardConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DashboardConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, DashboardConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DashboardConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DashboardConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DashboardConfigs
   * const dashboardConfig = await prisma.dashboardConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DashboardConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, DashboardConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DashboardConfigs and returns the data updated in the database.
   * @param {DashboardConfigUpdateManyAndReturnArgs} args - Arguments to update many DashboardConfigs.
   * @example
   * // Update many DashboardConfigs
   * const dashboardConfig = await prisma.dashboardConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DashboardConfigs and only return the `key`
   * const dashboardConfigWithKeyOnly = await prisma.dashboardConfig.updateManyAndReturn({
   *   select: { key: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DashboardConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DashboardConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DashboardConfig.
   * @param {DashboardConfigUpsertArgs} args - Arguments to update or create a DashboardConfig.
   * @example
   * // Update or create a DashboardConfig
   * const dashboardConfig = await prisma.dashboardConfig.upsert({
   *   create: {
   *     // ... data to create a DashboardConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DashboardConfig we want to update
   *   }
   * })
   */
  upsert<T extends DashboardConfigUpsertArgs>(args: Prisma.SelectSubset<T, DashboardConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__DashboardConfigClient<runtime.Types.Result.GetResult<Prisma.$DashboardConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DashboardConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DashboardConfigCountArgs} args - Arguments to filter DashboardConfigs to count.
   * @example
   * // Count the number of DashboardConfigs
   * const count = await prisma.dashboardConfig.count({
   *   where: {
   *     // ... the filter for the DashboardConfigs we want to count
   *   }
   * })
  **/
  count<T extends DashboardConfigCountArgs>(
    args?: Prisma.Subset<T, DashboardConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DashboardConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DashboardConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DashboardConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DashboardConfigAggregateArgs>(args: Prisma.Subset<T, DashboardConfigAggregateArgs>): Prisma.PrismaPromise<GetDashboardConfigAggregateType<T>>

  /**
   * Group by DashboardConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DashboardConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DashboardConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DashboardConfigGroupByArgs['orderBy'] }
      : { orderBy?: DashboardConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DashboardConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDashboardConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DashboardConfig model
 */
readonly fields: DashboardConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DashboardConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DashboardConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DashboardConfig model
 */
export interface DashboardConfigFieldRefs {
  readonly key: Prisma.FieldRef<"DashboardConfig", 'String'>
  readonly data: Prisma.FieldRef<"DashboardConfig", 'Json'>
}
    

// Custom InputTypes
/**
 * DashboardConfig findUnique
 */
export type DashboardConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * Filter, which DashboardConfig to fetch.
   */
  where: Prisma.DashboardConfigWhereUniqueInput
}

/**
 * DashboardConfig findUniqueOrThrow
 */
export type DashboardConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * Filter, which DashboardConfig to fetch.
   */
  where: Prisma.DashboardConfigWhereUniqueInput
}

/**
 * DashboardConfig findFirst
 */
export type DashboardConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * Filter, which DashboardConfig to fetch.
   */
  where?: Prisma.DashboardConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DashboardConfigs to fetch.
   */
  orderBy?: Prisma.DashboardConfigOrderByWithRelationInput | Prisma.DashboardConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DashboardConfigs.
   */
  cursor?: Prisma.DashboardConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DashboardConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DashboardConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DashboardConfigs.
   */
  distinct?: Prisma.DashboardConfigScalarFieldEnum | Prisma.DashboardConfigScalarFieldEnum[]
}

/**
 * DashboardConfig findFirstOrThrow
 */
export type DashboardConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * Filter, which DashboardConfig to fetch.
   */
  where?: Prisma.DashboardConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DashboardConfigs to fetch.
   */
  orderBy?: Prisma.DashboardConfigOrderByWithRelationInput | Prisma.DashboardConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DashboardConfigs.
   */
  cursor?: Prisma.DashboardConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DashboardConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DashboardConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DashboardConfigs.
   */
  distinct?: Prisma.DashboardConfigScalarFieldEnum | Prisma.DashboardConfigScalarFieldEnum[]
}

/**
 * DashboardConfig findMany
 */
export type DashboardConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * Filter, which DashboardConfigs to fetch.
   */
  where?: Prisma.DashboardConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DashboardConfigs to fetch.
   */
  orderBy?: Prisma.DashboardConfigOrderByWithRelationInput | Prisma.DashboardConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DashboardConfigs.
   */
  cursor?: Prisma.DashboardConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DashboardConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DashboardConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DashboardConfigs.
   */
  distinct?: Prisma.DashboardConfigScalarFieldEnum | Prisma.DashboardConfigScalarFieldEnum[]
}

/**
 * DashboardConfig create
 */
export type DashboardConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * The data needed to create a DashboardConfig.
   */
  data: Prisma.XOR<Prisma.DashboardConfigCreateInput, Prisma.DashboardConfigUncheckedCreateInput>
}

/**
 * DashboardConfig createMany
 */
export type DashboardConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DashboardConfigs.
   */
  data: Prisma.DashboardConfigCreateManyInput | Prisma.DashboardConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DashboardConfig createManyAndReturn
 */
export type DashboardConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * The data used to create many DashboardConfigs.
   */
  data: Prisma.DashboardConfigCreateManyInput | Prisma.DashboardConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DashboardConfig update
 */
export type DashboardConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * The data needed to update a DashboardConfig.
   */
  data: Prisma.XOR<Prisma.DashboardConfigUpdateInput, Prisma.DashboardConfigUncheckedUpdateInput>
  /**
   * Choose, which DashboardConfig to update.
   */
  where: Prisma.DashboardConfigWhereUniqueInput
}

/**
 * DashboardConfig updateMany
 */
export type DashboardConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DashboardConfigs.
   */
  data: Prisma.XOR<Prisma.DashboardConfigUpdateManyMutationInput, Prisma.DashboardConfigUncheckedUpdateManyInput>
  /**
   * Filter which DashboardConfigs to update
   */
  where?: Prisma.DashboardConfigWhereInput
  /**
   * Limit how many DashboardConfigs to update.
   */
  limit?: number
}

/**
 * DashboardConfig updateManyAndReturn
 */
export type DashboardConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * The data used to update DashboardConfigs.
   */
  data: Prisma.XOR<Prisma.DashboardConfigUpdateManyMutationInput, Prisma.DashboardConfigUncheckedUpdateManyInput>
  /**
   * Filter which DashboardConfigs to update
   */
  where?: Prisma.DashboardConfigWhereInput
  /**
   * Limit how many DashboardConfigs to update.
   */
  limit?: number
}

/**
 * DashboardConfig upsert
 */
export type DashboardConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * The filter to search for the DashboardConfig to update in case it exists.
   */
  where: Prisma.DashboardConfigWhereUniqueInput
  /**
   * In case the DashboardConfig found by the `where` argument doesn't exist, create a new DashboardConfig with this data.
   */
  create: Prisma.XOR<Prisma.DashboardConfigCreateInput, Prisma.DashboardConfigUncheckedCreateInput>
  /**
   * In case the DashboardConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DashboardConfigUpdateInput, Prisma.DashboardConfigUncheckedUpdateInput>
}

/**
 * DashboardConfig delete
 */
export type DashboardConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
  /**
   * Filter which DashboardConfig to delete.
   */
  where: Prisma.DashboardConfigWhereUniqueInput
}

/**
 * DashboardConfig deleteMany
 */
export type DashboardConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DashboardConfigs to delete
   */
  where?: Prisma.DashboardConfigWhereInput
  /**
   * Limit how many DashboardConfigs to delete.
   */
  limit?: number
}

/**
 * DashboardConfig without action
 */
export type DashboardConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DashboardConfig
   */
  select?: Prisma.DashboardConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DashboardConfig
   */
  omit?: Prisma.DashboardConfigOmit<ExtArgs> | null
}
